#!/usr/bin/perl
#
# unwrap
#
# remove line wrapping from text files
#

use strict;
use English;

my $myFile = @ARGV[0];
my $myLine = '';
my $outLine = '';
my $myLength = 0;
my $myEnd = '';

open (INPUTFILE, $myFile) || die "cannot open $myFile $1";

foreach $myLine (<INPUTFILE>) {
	chomp $myLine;
	
	open (OUTPUTFILE, "> SF356358.
	while ($myLength < 5001) {
		
	# collect and concatenate the lines until it
	# ends with a "
	$myEnd = substr($myLine, -1, 1);
	$outLine .= ' ' . $myLine;

	# if this line ends with a " then just write it out
	if ($myEnd eq '"') {
		print "$outLine\n";
		$outLine = '';
	}

}