#!/bin/bash
#
# tmk
# make a bzip2 tarball out of a directory

function tmk {
	if [[ "$1" == */* ]]; then
		length=`expr length "$1"`
		length=`expr $length - 1`
		directory=${1:0:$length}
	else
		directory="$1"
	fi
	tar -cvjf "$directory".tar.bz2 $directory/
	rm -rf $directory/
}