#! /bin/bash
#
# wrap
#
# alter line-wrapping of text files
#

if [ '$1' ]; then
	length=$1

else
	length=60   ## adjust to taste
fi
while IFS= read -r LINE
do
  case $LINE in
      "") echo $line; echo; line= ;;
      *) for word in $LINE
         do
           if [ $(( ${#line} + ${#word} )) -gt $length ]
           then
               echo "$line"
               line=$word
           else
               line=${line:+$line }$word
           fi
         done
         ;;
  esac
done < $2
echo ${line:+$line } 